insert into category (categoryId, categoryName) values (1, 'Progressive');
insert into category (categoryId, categoryName) values (2, 'dynamic');
insert into category (categoryId, categoryName) values (3, '6th generation');
insert into category (categoryId, categoryName) values (4, 'toolset');
insert into category (categoryId, categoryName) values (5, 'Visionary');
insert into category (categoryId, categoryName) values (6, 'systemic');
insert into category (categoryId, categoryName) values (7, 'matrix');
insert into category (categoryId, categoryName) values (8, 'Sharable');
insert into category (categoryId, categoryName) values (9, 'knowledge base');
insert into category (categoryId, categoryName) values (10, 'hierarchy');
insert into category (categoryId, categoryName) values (11, 'multimedia');
insert into category (categoryId, categoryName) values (12, 'hybrid');
insert into category (categoryId, categoryName) values (13, 'Organized');
insert into category (categoryId, categoryName) values (14, 'Focused');
insert into category (categoryId, categoryName) values (15, 'matrices');
